"""add description field to composition and collection

Revision ID: 15c22595b58b
Revises: 4d767fd7d13f
Create Date: 2023-10-11 10:32:01.019389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c22595b58b'
down_revision = '4d767fd7d13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
