"""add columns for compression of tracks

Revision ID: 1d8272daf3a1
Revises: ba678a7526be
Create Date: 2024-03-01 10:55:02.817824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8272daf3a1'
down_revision = 'ba678a7526be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compress_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('needs_compress', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('needs_compress')
        batch_op.drop_column('compress_path')

    # ### end Alembic commands ###
