"""opentocontribution col

Revision ID: 2227d92b1537
Revises: b2aca590b575
Create Date: 2023-04-12 16:15:13.935088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2227d92b1537'
down_revision = 'b2aca590b575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opentocontrib', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_column('opentocontrib')

    # ### end Alembic commands ###
