"""add new column at track table with user uid

Revision ID: 2f01ba679000
Revises: 15c22595b58b
Create Date: 2023-10-16 10:43:52.918950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f01ba679000'
down_revision = '15c22595b58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('track', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('user_uid', sa.String(length=22)))
     # Add the "User UID" column to the "Track" table
    op.add_column('track', sa.Column('user_uid', sa.String(length=22)))

    # Create a connection to the database
    connection = op.get_bind()

      # Update the "User UID" values for existing tracks
    connection.execute(sa.text(
       "UPDATE track AS t "
        "JOIN user AS u ON t.user_id = u.id "
        "SET t.user_uid = u.uid"
    ))               

   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('user_uid')

    # ### end Alembic commands ###
