"""create collections

Revision ID: 303d3a4da2d3
Revises: e8773f50a347
Create Date: 2023-06-14 14:00:44.932628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303d3a4da2d3'
down_revision = 'e8773f50a347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privacy', sa.Enum('public', 'onlyreg', 'private', name='compprivacy'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'collection', ['collection_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('collection_id')

    op.drop_table('collection')
    # ### end Alembic commands ###
