"""add contributors

Revision ID: 40e034f7d1f7
Revises: 
Create Date: 2023-03-24 16:07:13.812196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e034f7d1f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), server_default='4', nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.alter_column('privacy',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.alter_column('privacy',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('contributor')
    # ### end Alembic commands ###
