"""add latency field to composition and track table

Revision ID: 4ae53492ae9d
Revises: 4d767fd7d13f
Create Date: 2023-09-13 11:14:51.524389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae53492ae9d'
down_revision = '4d767fd7d13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latency', sa.Integer(), nullable=False))

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latency', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('latency')

    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_column('latency')

    # ### end Alembic commands ###
