"""metadata pydub and automatic anotations with essentia

Revision ID: bf799e6c655b
Revises: cf41748e7601
Create Date: 2025-01-29 10:55:54.799060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf799e6c655b'
down_revision = 'cf41748e7601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('file_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('file_metadata')
        batch_op.drop_column('is_processed')

    # ### end Alembic commands ###
