"""allow templates and clone

Revision ID: cf41748e7601
Revises: e7783ca0ab64
Create Date: 2024-10-30 13:30:13.809440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf41748e7601'
down_revision = 'e7783ca0ab64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cloned_from', sa.String(length=22), nullable=True))

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloned_from', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('cloned_from')

    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_column('cloned_from')
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
