"""add annotations to tracks and compositions

Revision ID: e7783ca0ab64
Revises: 6cfffbb060e9
Create Date: 2024-04-17 10:47:28.265523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7783ca0ab64'
down_revision = '6cfffbb060e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=22), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('composition_uid', sa.String(length=22), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_added', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['composition_uid'], ['composition.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('track_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=22), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('track_uid', sa.String(length=22), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('custom_added', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['track_uid'], ['track.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_annotation')
    op.drop_table('comp_annotation')
    # ### end Alembic commands ###
